### ISSUE TITLE
Content Sections: Hardware Section

### ISSUE THREAD

**Issue by sublayerio** [armada-alliance/armada-alliance#108]
Make it easy for a SPO to:

1. Define a list of hardware that they're using with approx pricing.
2. There will be a generalised list of hardware that can be referenced from within the defined hardware list. This way we can define detailed information about certain hardware products that are popular and give them their own page to look at. This also prevents the SPO from having to do that work.
3. Display total investment (besides pledge) to show delegators what the SPO's complete investment is. 

Example format:
```yaml
---
template: PoolDetailPage
ticker: SBLYR
memberSince: 2021-04-18
identities: 
    - id: sublayerio
      role: spo
contentSections:
  - type: HardwareSection
    items:
      - id: raspberry-pi-4-8gb
        name: Raspberry Pi 4 8GB
        url: https://www.amazon.nl/gp/product/B0899VXM8F/ref=ppx_yo_dt_b_asin_title_o08_s01?ie=UTF8&psc=1
        quantity: 2
        price: 86
        currency: EUR
      - id: mac-mini-m1
        name: Apple Mac Mini M1
        url: https://www.apple.com/shop/buy-mac/mac-mini/apple-m1-chip-with-8-core-cpu-and-8-core-gpu-256gb
        quantity: 1
        price: 800
        currency: EUR
      - url: https://www.amazon.nl/gp/product/B07G3KRZBY/ref=ppx_yo_dt_b_asin_title_o05_s00?ie=UTF8&psc=1
        name: Crucial BX500 Internal SSD 120GB
        quantity: 2
        price: 45.30
        currency: EUR
      - url: https://www.amazon.nl/gp/product/B07H95Z21P/ref=ppx_yo_dt_b_asin_title_o06_s00?ie=UTF8&psc=1
        name: Waveshare Power Over Ethernet HAT for Raspberry Pi 3B+ and 802.3af PoE Network with Fan Control and Isolated Switched-Mode
        quantity: 2
        price: 37.99
        currency: EUR
      - url: https://www.amazon.nl/gp/product/B00XLAZODE/ref=ppx_yo_dt_b_asin_title_o07_s00?ie=UTF8&psc=1
        name: StarTech. com USB 3.1 to 2.5" (6.4cm) SATA III Adapter Cable with UASP - USB 3.1 to SATA SSD/HDD Converter/Adapter Cable
        quantity: 2
        price: 26.95
        currency: EUR
      - url: https://www.amazon.nl/gp/product/B083FP9JRY/ref=ppx_yo_dt_b_asin_title_o08_s01?ie=UTF8&psc=1
        name: GeeekPi Raspberry Pi Cluster Case
        quantity: 1
        price: 39.99
        currency: EUR
      - url: https://www.amazon.nl/gp/product/B01N4VPGXZ/ref=ppx_yo_dt_b_asin_title_o08_s01?ie=UTF8&psc=1
        name: UTP Cables
        quantity: 1
        price: 13.23
        currency: EUR
      - url: https://www.bol.com/nl/nl/p/ubiquiti-unifi-switch-fully-managed-netwerkswitch-8-poorten-60w/9200000073914232/?s2a=
        name: Ubiquiti Unifi Switch Fully Managed 60W
        quantity: 1
        price: 111
        currency: EUR
      - url: https://shop.ledger.com/products/ledger-nano-s
        name: Ledger Nano S
        quantity: 1
        price: 59
        currency: EUR
---
```
